#!/bin/bash
### BEGIN INIT INFO
# Provides:          www-backup
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: backup www files
# Description:       Back up on OVH server
### END INIT INFO

case "$1" in 
start)
   /usr/local/bin/www-backup.sh &
   echo $!>/var/run/www-backup.pid
   ;;
stop)
   kill `cat /var/run/www-backup.pid`
   rm /var/run/www-backup.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/www-backup.pid ]; then
      echo www-backup is running, pid=`cat /var/run/www-backup.pid`
   else
      echo www-backup is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 